### ISSUE TITLE
Generate lambo.png but without materials surface

### ISSUE THREAD

**Issue by Icarus0xff** [hunterloftis/pbr#18]
Forgive my poor English,

After I run `./pbr fixtures/models/lambo.obj -heat lambo-heat.png -lon 4 -lat 0.1  -rad 2500 -lens 50 -fstop 1.4 -target=-0.2,0.5,0.4 -dist 9.6 -focus=-1,0.67,-0.56 -direct 0 -width 200 -height 200 -complete 8` it will generate a lambo.png with black-white lambo picture but without any color and surface on the model. So I want to ask how to generate a model with materials surface?

**Comment by hunterloftis** [comment]
Hi, no worries about your English, it's very good.

The way .obj files get materials is by referencing .mtl files. So if you have a given lambo.obj file, open it up, and you'll see something like this near the top:

```
# Blender v2.74 (sub 0) OBJ File: ''
# www.blender.org
mtllib lamborghini-aventador-webgl.mtl
```

That `mtllib` line is the material file reference, and it needs to be in the same directory as the .obj file. Similarly, the .mtl file will reference textures (jpegs or pngs), which also need to exist and in the same directory.
