### ISSUE TITLE
make fixtures Makefile:11 fixtures Error 2

### ISSUE THREAD

**Issue by omac777** [hunterloftis/pbr#19]
It displays progress inflating ...
```
  inflating: fixtures/images/satara.hdr
  inflating: fixtures/images/ennis.hdr

```
then errors out with:
`make: *** [Makefile:11: fixtures] Error 2`

This same error occurs in both linux and windows 7 msys2 shell with go1.10rc1.

**Comment by hunterloftis** [comment]
Thanks for this! Hard to test when I already have an existing /fixtures directory in the project and can't just cp -r the whole directory elsewhere to test because of GOPATH.

Looks like dropbox uses absolute paths in their zips. I just excluded `/` to work around that. PR coming.
