### ISSUE TITLE
sample falcon.png is entirely black

### ISSUE THREAD

**Issue by omac777** [hunterloftis/pbr#20]
After running:
`./pbr fixtures/models/falcon.obj -lat 0.5 -lon 0.5 -complete 5`

I opened falcon.png and it was entirely black.

Same results in both linux and windows 7 msys2 shell with go1.10rc1.

**Comment by hunterloftis** [comment]
Let's try a different angle and a specific distance, just to be sure. Here's what I'm doing:

```
~/code/src/github.com/hunterloftis/pbr (master) 🐹  go version
go version go1.9.3 darwin/amd64
~/code/src/github.com/hunterloftis/pbr (master) 🐠  ./pbr fixtures/models/falcon.obj -lat 0.3 -lon=-0.6 -dist 1200 -complete 1
```

![falcon](https://user-images.githubusercontent.com/364501/35575601-c68e81bc-05aa-11e8-8a1f-9133d004f950.png)

I'll try with 1.10rc1 in just a minute.

**Comment by hunterloftis** [comment]
I get an identical result with this:

```
~/code/src/github.com/hunterloftis/pbr (master) 🐠  go1.10beta2 build ./cmd/pbr
~/code/src/github.com/hunterloftis/pbr (master) 🐍  go1.10beta2 version
go version go1.10beta2 darwin/amd64
~/code/src/github.com/hunterloftis/pbr (master) 🐯  ./pbr fixtures/models/falcon.obj -lat 0.3 -lon=-0.6 -dist 1200 -complete 1
19.5s, samples (0.5 mil, 23/ms), rays (1.5 mil, 3.2/sample) [ 1 s/px ===>      falcon.png ]
~/code/src/github.com/hunterloftis/pbr (master) 🐧  open falcon.png
```

Are we rendering the exact same file? What's the md5 of your falcon.obj?

```
~/code/src/github.com/hunterloftis/pbr (master) 🐺  md5 fixtures/models/falcon.obj
MD5 (fixtures/models/falcon.obj) = 7e86dfba03e61c169ceaf85b842e1175
```

**Comment by hunterloftis** [comment]
I think this was probably fixed by https://github.com/hunterloftis/pbr/pull/21 - fixtures weren't being downloaded properly.
