### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by shazow** [hunterloftis/pbr#24]
Hey, excellent work. Stumbled from /r/golang.

You've done a lot of work transcribing various algorithms and properties, I'd love to refer/use some of this someday.

Any plans to add a LICENSE to this repo?

If you don't have preferences, I'd suggest MIT or BSD. I can send a PR if you'd like.

**Comment by hunterloftis** [comment]
Done! MIT :)

**Comment by shazow** [comment]
Yay, good choice. :)
